repos:
  - repo: https://github.com/godaddy/tartufo
    rev: 540d9b2a184db4e6c2e273973ecacbbf40f593d4  # frozen: v4.0.0
    hooks:
      - id: tartufo
  - repo: https://github.com/PyCQA/bandit
    rev: '1ed79063e3672a1c6d91ee27cb648e07a7465344' # 1.74
    hooks:
      - id: bandit
